# Crea una aplicación Drupal con una base de datos MySQL
# Uso: docker-compose up -d
# Nota: el nombre de la base es "mysql"

version: "2"
services:
  web:
    image: drupal:8.0.6-apache
    ports:
      - "8380:80"
    links:
      - mysql
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
